{
 "title": "OTUS Network",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "DB Master (CPU)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"db-slave1\"}[1m])"
    }
   ]
  },
  {
   "title": "DB Slave1 (CPU)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"db-master\"}[1m])"
    }
   ]
  },
  {
   "title": "Memory Usage (Master)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"db-master\"}",
     "legendFormat": "Master"
    }
   ]
  },
  {
   "title": "Memory Usage (Slave1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"db-slave1\"}",
     "legendFormat": "Slave-1"
    }
   ]
  },
  {
   "title": "Network Usage (Master)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"db-master\",interface=\"eth0\"}[1m])",
     "legendFormat": "Master Transmit"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"db-master\",interface=\"eth0\"}[1m])",
     "legendFormat": "Master Receive"
    }
   ]
  },
  {
   "title": "Network Usage (Slave1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"db-slave1\",interface=\"eth0\"}[1m])",
     "legendFormat": "Slave-1 Transmit"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"db-slave1\",interface=\"eth0\"}[1m])",
     "legendFormat": "Slave-1 Receive"
    }
   ]
  }
 ]
}